## Operaciones en Numpy

In [1]:
import numpy as np

In [5]:
#Creando lista en Python
lista = [1,2]
lista

[1, 2]

In [6]:
#multiplicando por 2 lista en Python
lista *2

[1, 2, 1, 2]

> Esto es algo que no es viable

Pero veamos que hace Numpy

In [7]:
#Creando array
arr1 = np.arange(0,10)

#Creando copia
arr2 = arr1.copy()

### Vamos a hacerle algunas operaciones matematicas

In [8]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
2*arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### *Esta es la ventaja de Numpy*

Que se pueda realizar operaciones sumamente complejas 

In [11]:

arr1 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
1/arr1 

/tmp/ipykernel_116025/201457648.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr1


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

### Precaución

No detiene la operación pero nos muestra que hay un error, **porque no se puede dividir entre 0**

>Solo el elemento que está mal lo pone con inf

In [13]:
arr1**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
arr1+arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
arr1*arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [16]:
arr1/arr2

/tmp/ipykernel_116025/3323896316.py:1: RuntimeWarning: invalid value encountered in divide
  arr1/arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

*Como se puede observar arroja un error pero sigue ejecutando la operación*

>El error solo lo pone como nan

## Veamos que pasa con matrices

In [18]:
matriz = arr1.reshape(2,5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
matriz2 = matriz.copy()
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [21]:
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [23]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Hay otra operación importante en **Algebra Lineal**
es el ***producto punto***

In [24]:
#Producto punto
np.matmul(matriz,matriz2)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 5)

El tipo de dimensiones no son las apropiadas
Hay que transponer la matriz 2

In [25]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [27]:
#Producto punto
np.matmul(matriz,matriz2.T)


array([[ 30,  80],
       [ 80, 255]])

In [28]:
#Otra forma de hacer el producto punto
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

### Documentación sobre operaciones en Numpy
https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations


In [30]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
#Suma de elementos del array
matriz.sum()

45

In [32]:
#Suma de columnas
#Reminder axis = 0 hace que colapsen las filas
matriz.sum(0)


array([ 5,  7,  9, 11, 13])

In [33]:
#Suma de filas
#Recuerda axis = 1 hace que colapsen las columnas
matriz.sum(axis=1)

array([10, 35])

In [34]:
#Suma de filas
#Recuerda axis = 1 hace que colapsen las columnas
matriz.sum(1)

array([10, 35])

In [36]:
#Broadcasting = Operacion entre array y escalar
matriz*1.6

array([[ 0. ,  1.6,  3.2,  4.8,  6.4],
       [ 8. ,  9.6, 11.2, 12.8, 14.4]])

In [37]:
#Multiplicación de todos los elementos
matriz.prod()

0

In [38]:
#Creando array
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
#Indexing
data[0, 1]

2

In [43]:
#Slicing
data[1:3]

array([[3, 4],
       [5, 6]])

In [42]:
#Slicing
data[0:2, 0]

array([1, 3])

![axis](images/numpy000.jpg)

In [45]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [46]:
data.max(axis=0)

array([5, 6])

In [47]:
data.max(axis=1)

array([2, 5, 6])