# Condiciones en Numpy

In [1]:
import numpy as np

In [3]:
#Creando array
arr1 = np.linspace(1,10,10, dtype='int8')
print(f'Array = {arr1}')

Array = [ 1  2  3  4  5  6  7  8  9 10]


In [5]:
#Aplicando condicionales
print('Array 1 > 5')
print(f'Array = \n{arr1}')
print(f'Condition = \n{arr1>5}')
#Me arroja una lista booleana


Array 1 > 5
Array = 
[ 1  2  3  4  5  6  7  8  9 10]
Condition = 
[False False False False False  True  True  True  True  True]


In [9]:
#Guardando la condicional
condicion = arr1>5

#dandole utilidad a la condición filtrando 
#los que cumplan con la condición
arr1_filtrado = arr1[condicion]
print('Condición Array 1 > 5\n')
print(f'Array = {arr1}')
print(f'Array filtrado = {arr1_filtrado}')

#metodo manual
print('Condición Array 1 > 5\n')
print(f'Array filtrado manualmente')
print(f'arr1[arr1>5] = {arr1[arr1>5]}')

Condición Array 1 > 5

Array = [ 1  2  3  4  5  6  7  8  9 10]
Array filtrado = [ 6  7  8  9 10]
Condición Array 1 > 5

Array filtrado manualmente
arr1[arr1>5] = [ 6  7  8  9 10]


### **Podemos manejar condiciones más complejas**

Aquí le estoy diciendo que quiero los valores mayores a **5** y menores a **9**

In [13]:
#condiciones complejas

arr1[(arr1>5)&(arr1<9)]

array([], dtype=int8)

Aquí le estoy diciendo que quiero que los valores mayores a **5** sean modificados a 99

In [14]:
#condiciones complejas
arr1[arr1>5] = 99
arr1

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

Aquí le pedimos que me muestre solo ***los valores que son igual*** a **99**

In [15]:
arr1[arr1==99]

array([99, 99, 99, 99, 99], dtype=int8)

### Reto:

Crea tu propio array y aplicale unas condiciones


In [23]:
# Array
arr_dens=np.random.randint(1,20,size=(5,6))
print(f'Array = \n{arr_dens}\n')

#Condicion 1 números pares o mayores a 10
cond1=arr_dens[(arr_dens%2==0) | (arr_dens>10)]
print(f'Condición 1 = \n{cond1}\n')

#Condicion 2 números pares
cond2=arr_dens[arr_dens%2==0]
print(f'Condición 2 = \n{cond2}\n')

#Copia del arreglo
cp_arrden = arr_dens.copy()

#Cambiando los impares por su valor multiplicado por 2
cp_arrden[cp_arrden%2!=0]*=2
print(f'Array original = \n{arr_dens}\n')
print(f'Array condicionado = \n{cp_arrden}\n')


Array = 
[[19 12 14 13  8 13]
 [16 16 18  7 14 10]
 [14 14 10 13 14  4]
 [ 1  6 11 10 10  8]
 [16  2 17  5 13 12]]

Condición 1 = 
[19 12 14 13  8 13 16 16 18 14 10 14 14 10 13 14  4  6 11 10 10  8 16  2
 17 13 12]

Condición 2 = 
[12 14  8 16 16 18 14 10 14 14 10 14  4  6 10 10  8 16  2 12]

Array original = 
[[19 12 14 13  8 13]
 [16 16 18  7 14 10]
 [14 14 10 13 14  4]
 [ 1  6 11 10 10  8]
 [16  2 17  5 13 12]]

Array condicionado = 
[[38 12 14 26  8 26]
 [16 16 18 14 14 10]
 [14 14 10 26 14  4]
 [ 2  6 22 10 10  8]
 [16  2 34 10 26 12]]

