## Funciones Principales NUMPY

In [1]:
import numpy as np

In [6]:
#Vector de 10 elementos
array = np.random.randint(1,20,10)

#Convirtiendo a la matriz
matriz = array.reshape(2,5)
print(f'Matriz = \n{matriz}\nTamaño = {matriz.shape}')

Matriz = 
[[15  1 19 14 19]
 [ 1 19  1 15  1]]
Tamaño = (2, 5)


In [16]:
#Max    Número mas grande
#Imprimiendo datos de la matriz
print(f'Matriz = \n{matriz}\nTamaño = {matriz.shape}\n')

#Aplicandolo a una matriz
max_num = matriz.max()
print(f'Maximo de Matriz = {max_num}')

#Indicando que máximos que queremos 

#Columnas
max_num = matriz.max(0)
print(f'Maximo por columna = {max_num}')
#Filas
max_num = matriz.max(1)
print(f'Maximo por filas = {max_num}')


Matriz = 
[[15  1 19 14 19]
 [ 1 19  1 15  1]]
Tamaño = (2, 5)

Maximo de Matriz = 19
Maximo por columna = [15 19 19 15 19]
Maximo por filas = [19 19]


## Importante:

Los ejes en Numpy son axis(x,y,z,w...) donde:
- x es el eje de las filas (o rows) y es 0
- y es el eje de las columnas y es 1
- z es el eje de la profundidad y es 2
- Sucesivamente
  
![Axes](images/axes_00.jpg "Representación de ejes")


#### Algunas operaciones en numpy se rigen por:

axis = 0 Hace que se colapsan las filas y solo queda una fila

![Axis=0](images/axes_01.jpg "Colapsando en filas")


axis = 1 Hace que colapsen las columnas quedando solo una columna

![Axis=1](images/axes_02.jpg "Colapsando en columnas")

In [36]:
#argmax me devuelve el indice del número mayor mas próximo
#Encontrando el indice del max en vector
max_ind = array.argmax()
print(f'Array = \n{array}\n\
El indice del número mayour es = {max_ind}\n')

#Encontrando el indice del max en matriz
max_ind = matriz.argmax()   #global
print(f'Matriz = \n{matriz}\n\
El indice del número mayor es = {max_ind}\n')

#Pero si queremos en columnas
print('Por columnas')
max_ind = matriz.argmax(0)  #columnas
print(f'Matriz = \n{matriz}\n\
El indice del numero mayor es = {max_ind}\n')

#Pero si queremos en filas
print('Por filas')
max_ind = matriz.argmax(1)  #columnas
print(f'Matriz = \n{matriz}\n\
El indice del numero mayor es = {max_ind}')


Array = 
[15  1 19 14 19  1 19  1 15  1]
El indice del número mayour es = 2

Matriz = 
[[15  1 19 14 19]
 [ 1 19  1 15  1]]
El indice del número mayor es = 2

Por columnas
Matriz = 
[[15  1 19 14 19]
 [ 1 19  1 15  1]]
El indice del numero mayor es = [0 1 0 1 0]

Por filas
Matriz = 
[[15  1 19 14 19]
 [ 1 19  1 15  1]]
El indice del numero mayor es = [2 1]


## Nota:

*Si queremos encontrar el **mayor de cada fila***
*tenenemos que **colapsar en columnas***

*Si queremos encontrar el **mayor de cada columna***
*tenemos que **colapsar en filas***

# NOTA IMPORTANTE

Para arrays de 1D esto puede no funcionar así,
tiene algunas particularidades

In [40]:
#Valor minimo de un vector
min_num = array.min()
print(f"Vector = {array}\n\
Valor minimo = {min_num}")

#Indice de valor minimo de un vector
min_index = array.argmin()
print(f'Indice del valor minimo de un vector = \
{min_index}\n')

#Valor minimo de una matriz
min_num = matriz.min()  #global
print(f'Matriz = \n{matriz}\n\
Valor minimo = {min_num}')
min_index = matriz.argmin()
print(f'Indice del valor minimo de una matriz = \
{min_index}\n')

#Valor minimo de una matriz por filas
print('Por filas')
min_num = matriz.min(1)  #filas
print(f'Matriz = \n{matriz}\n\
Valor minimo = {min_num}')
min_index = matriz.argmin(1)
print(f'Indice del valor minimo de una matriz = \
{min_index}\n')

#Valor minimo de una matriz por columnas
print('Por columnas')
min_num = matriz.min(0)  #filas
print(f'Matriz = \n{matriz}\n\
Valor minimo = {min_num}')
min_index = matriz.argmin(0)
print(f'Indice del valor minimo de una matriz = \
{min_index}')

Vector = [15  1 19 14 19  1 19  1 15  1]
Valor minimo = 1
Indice del valor minimo de un vector = 1

Matriz = 
[[15  1 19 14 19]
 [ 1 19  1 15  1]]
Valor minimo = 1
Indice del valor minimo de una matriz = 1

Por filas
Matriz = 
[[15  1 19 14 19]
 [ 1 19  1 15  1]]
Valor minimo = [1 1]
Indice del valor minimo de una matriz = [1 0]

Por columnas
Matriz = 
[[15  1 19 14 19]
 [ 1 19  1 15  1]]
Valor minimo = [ 1  1  1 14  1]
Indice del valor minimo de una matriz = [1 0 1 0 1]


In [41]:
#peak to peak
print(f'Vector = {array}')


Vector = [15  1 19 14 19  1 19  1 15  1]


El valor mas **pequeño** es **1** y el mas **grande** es **19**

In [43]:
print(f'La distancia peak to peak = {array.ptp()}')

La distancia peak to peak = 18


*Aqui puedo ver la distribución entre*
*valor mínimo y valor máximo*

In [49]:
#Hagamoslo a nivel matricial

#Imprimiendo matriz
print(f'Matriz = \n{matriz}\n')

#Buscando por columnas
peakMat=matriz.ptp(0)
print('Por columnas')
print(f'Peak to peak = {peakMat}\n')

#Buscando por filas
peakMat=matriz.ptp(1)
print('Por filas')
print(f'Peak to peak = {peakMat}')

Matriz = 
[[15  1 19 14 19]
 [ 1 19  1 15  1]]

Por columnas
Peak to peak = [14 18 18  1 18]

Por filas
Peak to peak = [18 18]



Un percentil es una medida estadística que indica el valor por debajo del cual se encuentra un porcentaje específico de observaciones en un conjunto de datos. Por ejemplo, el percentil 50, también conocido como la mediana, indica el valor que separa el 50% más bajo del 50% más alto de los datos. Los percentiles son útiles para comprender la distribución de los datos y para comparar diferentes conjuntos de datos. Se utilizan comúnmente en campos como la salud (por ejemplo, para evaluar el crecimiento de los niños) y en pruebas estandarizadas (por ejemplo, para evaluar el rendimiento académico).

In [53]:
#percentil
print(f'Vector = {array}')
print(f'Percentil 50 = {np.percentile(array,50)}')
print(f'Percentil 20 = {np.percentile(array,20)}')
print(f'Percentil 0 = {np.percentile(array,0)}')
print(f'Percentil 100 = {np.percentile(array,100)}')




Vector = [15  1 19 14 19  1 19  1 15  1]
Percentil 50 = 14.5
Percentil 20 = 1.0
Percentil 0 = 1.0
Percentil 100 = 19.0


OJO: Percentil toma el número de datos que hay

In [59]:
#Ordenar datos sort
array.sort()
array
print(f'Vector ordenado = {array}\n')
print(f'Como se pude ver el percentil 50 esta entre 14 y 15')

Vector ordenado = [ 1  1  1  1 14 15 15 19 19 19]

Como se pude ver el percentil 50 esta entre 14 y 15


## IMPORTANTE:

Hay que recordar que el método sort() modifica arrays

In [66]:
#Mediana
mediana = np.median(array) 
print(f'Mediana = {mediana}')
 
#Ordenando matriz mediana de matriz
matriz.sort()
print(f'Matriz = \n{matriz}')
mediana_mat = np.median(matriz)
print(f'Mediana de matriz = {mediana_mat}')

#Mediana de la matriz por columnas
mediana_mat = np.median(matriz,0)
print(f'Mediana de matriz por columnas = {mediana_mat}')

#Mediana de la matriz por filas
mediana_mat = np.median(matriz,1)
print(f'Mediana de matriz por filas = {mediana_mat}')


Mediana = 14.5
Matriz = 
[[ 1  1  1  1 14]
 [15 15 19 19 19]]
Mediana de matriz = 14.5
Mediana de matriz por columnas = [ 8.   8.  10.  10.  16.5]
Mediana de matriz por filas = [ 1. 19.]


Para calcular la mediana de un conjunto de datos, sigue estos pasos:

1. Ordena los datos de menor a mayor: Si tienes una lista de datos, arréglalos en orden ascendente.

2. Encuentra el valor medio: Si hay un número impar de datos, la mediana es simplemente el valor en el medio de la lista después de ordenarlos. Si hay un número par de datos, la mediana es el promedio de los dos valores medios.

Por ejemplo, si tienes los datos: 3, 6, 9, 12, 15. La mediana sería 9, ya que es el valor en el medio de la lista ordenada.

Si tienes los datos: 2, 4, 6, 8, 10, 12. La mediana sería (6 + 8) / 2 = 7, ya que hay un número par de datos y la mediana es el promedio de los dos valores medios (6 y 8).

In [67]:
#Desviación standard
desv_st =np.std(array)
print(f'Desviación estandard = {desv_st}')


Desviación estandard = 7.940403012442126



La desviación estándar es una medida de dispersión que indica cuánto varían los valores de un conjunto de datos respecto a la media. Cuanto mayor sea la desviación estándar, mayor será la dispersión de los datos alrededor de la media, y cuanto menor sea, menor será esa dispersión.

Para calcular la desviación estándar, sigue estos pasos:

1. Calcula la media: Suma todos los valores en el conjunto de datos y luego divídelo por el número total de valores. Esto te dará la media.

2. Calcula la diferencia entre cada valor y la media: Resta la media de cada valor en el conjunto de datos.

3. Eleva al cuadrado cada diferencia: Esto se hace para eliminar signos negativos y para enfatizar las desviaciones más grandes.

4. Calcula la media de los cuadrados de las diferencias: Suma todos los cuadrados de las diferencias y divide el resultado por el número total de valores.

5. Calcula la raíz cuadrada de la media de los cuadrados de las diferencias: Esta es la desviación estándar.

![Desviación standard](images/desv_st.jpg)


In [68]:
#Varianza
print(f'Vector = {array}\nVarianza = {np.var(array)}')

Vector = [ 1  1  1  1 14 15 15 19 19 19]
Varianza = 63.05


![Varianza](images/varianza.jpg)

*La varianza es la elevación al cuadrado de la desviación standard*

In [93]:
#Media
print(f'Vector = {array}\nMedia = {np.mean(array)}')

Vector = [ 1  1  1  1 14 15 15 19 19 19]
Media = 10.5


La media, también conocida como promedio, es una medida estadística que representa el valor típico o central de un conjunto de datos. Para calcular la media, sumas todos los valores en el conjunto de datos y luego divides esa suma por el número total de valores.

Por ejemplo, si tienes los siguientes datos: 2, 4, 6, 8, 10, la media sería:

![Media](images/media.jpg)

La media en este caso es 6, ya que es el valor que equitativamente distribuiría la suma total de los datos si todos fueran iguales. Es una medida útil para entender el valor central de un conjunto de datos.

In [95]:
#Concatenación
B = np.squeeze(B)
A = np.array([[1,2],[3,4]])
print(f'Matriz A = \n{A}\n')

B = np.array([5,6])
print(f'Matriz B = \n{B}')

C = np.concatenate((A,B),axis=0)

Matriz A = 
[[1 2]
 [3 4]]

Matriz B = 
[5 6]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

## No se puede concatenar en diferentes dimensiones

In [96]:
#Obteniendo dimensiones
B = np.squeeze(B)
print(f'Dimensión de A = {A.ndim}\nTamaño = {A.shape}')
print(f'Dimensión de B = {B.ndim}\nTamaño = {B.shape}\n')


Dimensión de A = 2
Tamaño = (2, 2)
Dimensión de B = 1
Tamaño = (2,)



In [97]:
#Expandiendo B a la misma dimensión de A
B = np.expand_dims(B,axis=0)

In [98]:
#Checando dimensiones
print(f'Dimensión de A = {A.ndim}\nTamaño = {A.shape}')
print(f'Dimensión de B = {B.ndim}\nTamaño = {B.shape}\n')
#Imprimiendo matrices
print(f'Matriz A = \n{A}\n')
print(f'Matriz B = \n{B}\n')

#Concatenando por filas de A y B
print('Concatenación por filas | Axis=0')
C = np.concatenate((A,B),axis=0)
print(f'Matriz C = \n{C}')


Dimensión de A = 2
Tamaño = (2, 2)
Dimensión de B = 2
Tamaño = (1, 2)

Matriz A = 
[[1 2]
 [3 4]]

Matriz B = 
[[5 6]]

Concatenación por filas | Axis=0
Matriz C = 
[[1 2]
 [3 4]
 [5 6]]


In [92]:
#Checando dimensiones
B = np.squeeze(B)
#Adaptando a B para que quede en forma de columna
B = np.expand_dims(B,axis=1)
print(f'Dimensión de A = {A.ndim}\nTamaño = {A.shape}')
print(f'Dimensión de B = {B.ndim}\nTamaño = {B.shape}\n')
#Imprimiendo matrices
print(f'Matriz A = \n{A}\n')
print(f'Matriz B = \n{B}\n')

#Concatenando por columnas de A y B
print('Concatenación por filas | Axis=0')
D = np.concatenate((A,B),axis=1)
print(f'Matriz C = \n{D}')

Dimensión de A = 2
Tamaño = (2, 2)
Dimensión de B = 2
Tamaño = (2, 1)

Matriz A = 
[[1 2]
 [3 4]]

Matriz B = 
[[5]
 [6]]

Concatenación por filas | Axis=0
Matriz C = 
[[1 2 5]
 [3 4 6]]


Para acondicionar una matriz podemos usar:
* Reshape
* Matriz transpuesta
* Expandir dimension

In [116]:
#Eliminando dimensiones innecesarias
B = np.squeeze(B)
B = np.expand_dims(B,axis=1)
#Checando dimensión y forma
print(f'Dimensión de A = {A.ndim}\nTamaño = {A.shape}')
print(f'Dimensión de B = {B.ndim}\nTamaño = {B.shape}\n')

#Imprimiendo matrices
print(f'Matriz A = \n{A}\n')
print(f'Matriz B = \n{B}\n')

#Otra forma es T => la transpuesta
#Aquí por la forma, usaremos la transpuesta
#B = np.transpose(B)
#B = B.T



#Concatenando por columnas de A y B
print('Concatenación por filas | Axis=0')

E = np.concatenate((A,B.T),axis=0)
print(f'Matriz C = \n{E}')

Dimensión de A = 2
Tamaño = (2, 2)
Dimensión de B = 2
Tamaño = (2, 1)

Matriz A = 
[[1 2]
 [3 4]]

Matriz B = 
[[5]
 [6]]

Concatenación por filas | Axis=0
Matriz C = 
[[1 2]
 [3 4]
 [5 6]]


## Es importante que verifiques las dimensiones de las matrices para hacer operaciones