# Shape & Reshape

In [1]:
#Importando Numpy
import numpy as np

In [4]:
#Creando un array 
arr1 = np.random.randint(1,10,size=(3,2))
print(f"Array 1:\n{arr1}\nTamaño = {arr1.shape}\nDimensión = {arr1.ndim}")

Array 1:
[[2 7]
 [7 5]
 [4 4]]
Tamaño = (3, 2)
Dimensión = 2


### *Aquí tenemos un array con:*

* 3 Filas
* 2 Columnas
* Y en **2** dimensiones

>Por lo tanto podemos decir que: ***shape(x,y,z)***

Nos hace pensar que tenemos un arreglo de:
* **x** Grupos principales
* **y** Subgrupos 
* **z** Elementos dentro de los subgrupos

In [14]:
#Haciendo Reshape
arr1 = arr1.reshape(1,6)
print(f"Array 1: {arr1}\nTamaño = {arr1.shape}\nDimensión = {arr1.ndim}")

#Otra forma de reshape
np.reshape(arr1,(2,3))

Array 1: [[2 7 7 5 4 4]]
Tamaño = (1, 6)
Dimensión = 2


array([[2, 7, 7],
       [5, 4, 4]])

### Cambiando la forma del arreglo

*numpy.reshape(x,y)*

*numpy.reshape(array,(2,3))*

El metodo reshape me ayuda a cambiar la forma de un arreglo

> **NOTA: tiene que contener los mismos elementos**

In [17]:
#Otra forma de reshape
np.reshape(arr1,(3,3))

ValueError: cannot reshape array of size 6 into shape (3,3)

In [33]:
#El error anterior nos muestra la NOTA

#Explorando mas
arr1 = arr1.reshape(3,2)
print(f'Array = \n{arr1}\nTamaño = {arr1.shape}\n')

#Vamos a decirle que lo haga como el lenguaje C
arr1 = np.reshape(arr1,(2,3),'C')
print(f'Array = \n{arr1}\nTamaño = {arr1.shape}\n')

Array = 
[[2 7]
 [7 5]
 [4 4]]
Tamaño = (3, 2)

Array = 
[[2 7 7]
 [5 4 4]]
Tamaño = (2, 3)



>C nos demuestra que lo hace por filas

In [35]:
#Reshape
#Explorando mas
arr1 = np.array([[2,4],[5,7],[7,4]])
print(f'Array = \n{arr1}\nTamaño = {arr1.shape}\n')

#Vamos a decirle que lo haga como el lenguaje Fortran
arr1 = np.reshape(arr1,(2,3),'F')
print(f'Array = \n{arr1}\nTamaño = {arr1.shape}\n')

Array = 
[[2 4]
 [5 7]
 [7 4]]
Tamaño = (3, 2)

Array = 
[[2 7 7]
 [5 4 4]]
Tamaño = (2, 3)



>Fortran nos demuestra que lo hace por columnas

In [38]:
#Diciendole que se base en la optimización de mi S.OSError
arr1 = np.reshape(arr1,(3,2),'A')
print(f'Array = \n{arr1}\nTamaño = {arr1.shape}\n')

Array = 
[[2 4]
 [5 7]
 [7 4]]
Tamaño = (3, 2)



>A nos ayuda a encontrar la optimización de mi sistema

### Lo mejor es tener conocimiento de como se hace

*Así que lo mas conveniente es escoger uno*. La clase sugiere usarlo en **C**, ya que **Python** está basado en **C**

### Reto:

*Crea un tensor de cualquier dimension y cambia la forma*

In [43]:
#Creando un tensor de 2*5*6*3
tensor = np.random.randint(2,100,size=(2,5,6,3))
print(f'Tensor = \n\n{tensor}\nTamaño = {tensor.shape}\nDimensión = {tensor.ndim}')

Tensor = 

[[[[85 34 89]
   [10 74 72]
   [ 4 82 66]
   [68  4 88]
   [55 53  5]
   [ 4 39 29]]

  [[26  5 87]
   [56 48 89]
   [89 99 63]
   [64 88 12]
   [38 12 48]
   [18 35 90]]

  [[26 88 32]
   [85 91 57]
   [71 89 59]
   [55 65 52]
   [85 11 48]
   [43 51 24]]

  [[22 79 62]
   [ 2 55 58]
   [22 98  4]
   [62 86 93]
   [37 61 65]
   [50 87 39]]

  [[17 56 42]
   [86 27 81]
   [28 48 36]
   [95 13 86]
   [71 70 66]
   [59 33 54]]]


 [[[40 93 58]
   [89 65 49]
   [32 25 59]
   [80 84 34]
   [55  2 86]
   [49 90 64]]

  [[62 65 60]
   [58 93 96]
   [78 35 97]
   [49 34 13]
   [66 54 35]
   [38 12 20]]

  [[55 46 69]
   [58 10 21]
   [ 4 76 71]
   [76 38 47]
   [62 80 65]
   [43 50 77]]

  [[38 88 28]
   [23 72 29]
   [78 93 54]
   [18 18 86]
   [63 14  7]
   [41 79 14]]

  [[83 28 32]
   [79 18 38]
   [ 3 18 67]
   [43 70 83]
   [63 83 64]
   [36 67 40]]]]
Tamaño = (2, 5, 6, 3)
Dimensión = 4


In [45]:
#Cambiando la forma de 2 * 5 * 6 * 3 a 6 * 10 * 3 en C
tensor = np.reshape(tensor,(6,10,3),'C')
print(f'Tensor = \n\n{tensor}\nTamaño = {tensor.shape}\nDimensión = {tensor.ndim}')

Tensor = 

[[[85 34 89]
  [10 74 72]
  [ 4 82 66]
  [68  4 88]
  [55 53  5]
  [ 4 39 29]
  [26  5 87]
  [56 48 89]
  [89 99 63]
  [64 88 12]]

 [[38 12 48]
  [18 35 90]
  [26 88 32]
  [85 91 57]
  [71 89 59]
  [55 65 52]
  [85 11 48]
  [43 51 24]
  [22 79 62]
  [ 2 55 58]]

 [[22 98  4]
  [62 86 93]
  [37 61 65]
  [50 87 39]
  [17 56 42]
  [86 27 81]
  [28 48 36]
  [95 13 86]
  [71 70 66]
  [59 33 54]]

 [[40 93 58]
  [89 65 49]
  [32 25 59]
  [80 84 34]
  [55  2 86]
  [49 90 64]
  [62 65 60]
  [58 93 96]
  [78 35 97]
  [49 34 13]]

 [[66 54 35]
  [38 12 20]
  [55 46 69]
  [58 10 21]
  [ 4 76 71]
  [76 38 47]
  [62 80 65]
  [43 50 77]
  [38 88 28]
  [23 72 29]]

 [[78 93 54]
  [18 18 86]
  [63 14  7]
  [41 79 14]
  [83 28 32]
  [79 18 38]
  [ 3 18 67]
  [43 70 83]
  [63 83 64]
  [36 67 40]]]
Tamaño = (6, 10, 3)
Dimensión = 3
